-- Sample PDF Upload Script for Industry Knowledge Library
-- This script shows how to manually insert PDF documents for testing

-- First, ensure the tables exist
-- Run scripts/setup-industry-knowledge.sql first if you haven't already

-- 1. Insert sample industry knowledge documents
INSERT INTO industry_knowledge_documents (
    id,
    title,
    description,
    category,
    subcategory,
    tags,
    file_path,
    file_size,
    file_type,
    processing_status,
    is_active
) VALUES 
(
    gen_random_uuid(),
    'Fire Safety Regulations 2024',
    'Comprehensive guide to fire safety requirements for residential buildings',
    'Compliance & Regulations',
    'Fire Safety',
    ARRAY['fire', 'safety', 'regulations', 'compliance', 'residential'],
    '/uploads/industry-knowledge/fire-safety-regulations-2024.pdf',
    2048576, -- 2MB
    'pdf',
    'completed',
    true
),
(
    gen_random_uuid(),
    'Section 20 Consultation Guide',
    'Step-by-step guide for major works consultation under Section 20',
    'Major Works',
    'Section 20',
    ARRAY['section20', 'consultation', 'major works', 'leaseholder', 'consultation'],
    '/uploads/industry-knowledge/section20-consultation-guide.pdf',
    1536000, -- 1.5MB
    'pdf',
    'completed',
    true
),
(
    gen_random_uuid(),
    'Leaseholder Rights and Responsibilities',
    'Comprehensive guide to leaseholder rights under UK law',
    'Leaseholder Relations',
    'Legal Rights',
    ARRAY['leaseholder', 'rights', 'responsibilities', 'legal', 'UK law'],
    '/uploads/industry-knowledge/leaseholder-rights-guide.pdf',
    3072000, -- 3MB
    'pdf',
    'completed',
    true
),
(
    gen_random_uuid(),
    'Building Maintenance Best Practices',
    'Industry best practices for building maintenance and repairs',
    'Maintenance & Repairs',
    'Best Practices',
    ARRAY['maintenance', 'repairs', 'best practices', 'building', 'industry'],
    '/uploads/industry-knowledge/maintenance-best-practices.pdf',
    2560000, -- 2.5MB
    'pdf',
    'completed',
    true
),
(
    gen_random_uuid(),
    'Service Charge Management Guide',
    'Complete guide to managing and calculating service charges',
    'Financial Management',
    'Service Charges',
    ARRAY['service charges', 'financial', 'management', 'calculation', 'budgeting'],
    '/uploads/industry-knowledge/service-charge-guide.pdf',
    1792000, -- 1.75MB
    'pdf',
    'completed',
    true
);

-- 2. Insert sample document chunks (these would normally be generated by the AI processor)
-- For testing purposes, we'll create some sample chunks

-- Get the document IDs we just created
DO $$
DECLARE
    doc_record RECORD;
    chunk_texts TEXT[] := ARRAY[
        'Fire safety is a critical aspect of residential building management. All buildings must comply with current fire safety regulations including proper fire detection systems, emergency lighting, and clear evacuation routes.',
        'Regular fire safety inspections are required by law. These should be conducted by qualified professionals and documented thoroughly. Any issues found must be addressed immediately.',
        'Fire safety equipment must be maintained in working order at all times. This includes fire extinguishers, smoke detectors, and fire alarm systems.',
        'Residents must be informed of fire safety procedures and evacuation plans. Regular fire drills should be conducted to ensure everyone knows what to do in an emergency.',
        'Building managers are responsible for ensuring all fire safety measures are properly implemented and maintained according to current regulations.'
    ];
    chunk_text TEXT;
    chunk_index INTEGER := 0;
BEGIN
    FOR doc_record IN SELECT id, title FROM industry_knowledge_documents WHERE processing_status = 'completed' LOOP
        
        -- Insert chunks for each document
        FOREACH chunk_text IN ARRAY chunk_texts LOOP
            INSERT INTO industry_knowledge_chunks (
                document_id,
                chunk_index,
                chunk_text,
                page_number,
                section_title,
                metadata
            ) VALUES (
                doc_record.id,
                chunk_index,
                chunk_text,
                (chunk_index / 2) + 1,
                CASE 
                    WHEN chunk_index = 0 THEN 'Introduction'
                    WHEN chunk_index = 1 THEN 'Regulatory Requirements'
                    WHEN chunk_index = 2 THEN 'Equipment Maintenance'
                    WHEN chunk_index = 3 THEN 'Resident Communication'
                    WHEN chunk_index = 4 THEN 'Manager Responsibilities'
                END,
                jsonb_build_object(
                    'chunkIndex', chunk_index,
                    'totalChunks', array_length(chunk_texts, 1),
                    'category', 'Compliance & Regulations',
                    'documentTitle', doc_record.title
                )
            );
            chunk_index := chunk_index + 1;
        END LOOP;
        
        chunk_index := 0; -- Reset for next document
    END LOOP;
END $$;

-- 3. Insert sample processing logs
INSERT INTO industry_knowledge_processing_logs (
    document_id,
    processing_step,
    status,
    processing_time_ms,
    error_message
) 
SELECT 
    id,
    'pdf_processing',
    'completed',
    5000, -- 5 seconds
    NULL
FROM industry_knowledge_documents 
WHERE processing_status = 'completed';

-- 4. Insert sample usage analytics
INSERT INTO industry_knowledge_usage (
    query_text,
    relevant_documents,
    response_accuracy_rating,
    user_feedback
) VALUES 
(
    'What are the fire safety requirements for my building?',
    ARRAY['Fire Safety Regulations 2024'],
    5,
    'Very helpful and accurate information about fire safety requirements'
),
(
    'How do I handle Section 20 consultation?',
    ARRAY['Section 20 Consultation Guide'],
    4,
    'Good guidance on the consultation process'
),
(
    'What are my rights as a leaseholder?',
    ARRAY['Leaseholder Rights and Responsibilities'],
    5,
    'Comprehensive explanation of leaseholder rights'
);

-- 5. Verify the data was inserted correctly
SELECT 
    'Documents' as table_name,
    COUNT(*) as record_count
FROM industry_knowledge_documents
UNION ALL
SELECT 
    'Chunks' as table_name,
    COUNT(*) as record_count
FROM industry_knowledge_chunks
UNION ALL
SELECT 
    'Processing Logs' as table_name,
    COUNT(*) as record_count
FROM industry_knowledge_processing_logs
UNION ALL
SELECT 
    'Usage Analytics' as table_name,
    COUNT(*) as record_count
FROM industry_knowledge_usage;

-- 6. Show sample document with chunks
SELECT 
    d.title,
    d.category,
    d.subcategory,
    d.tags,
    COUNT(c.id) as chunk_count,
    d.processing_status
FROM industry_knowledge_documents d
LEFT JOIN industry_knowledge_chunks c ON d.id = c.document_id
GROUP BY d.id, d.title, d.category, d.subcategory, d.tags, d.processing_status
ORDER BY d.title;
